### ISSUE TITLE
Cannot push to heroku

### ISSUE THREAD

**Issue by qzchenwl** [mwotton/heroku_haskell_demo#2]
I know this project from [Haskell on Heroku](http://www.yesodweb.com/blog/2011/07/haskell-on-heroku).
I tried to push to heroku, but got error.

```
$ git push heroku master
Counting objects: 8, done.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (8/8), 1.17 MiB, done.
Total 8 (delta 0), reused 0 (delta 0)

-----> Heroku receiving push
 !     Heroku push rejected, no Rails or Rack app detected

To git@heroku.com:deep-leaf-918.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:deep-leaf-918.git'
```

**Comment by mwotton** [comment]
Hm, that's odd. It should work fine if you have the gemfile, gemfile.lock and procfile.
Have you changed anything in the directory?

**Comment by qzchenwl** [comment]
I just remove the .git folder, and reinit it, then add files, then commit, then push. 
Both gemfile and gemfile.lock exist as empty file. Procfile exists.

No file changed except .git

**Comment by qzchenwl** [comment]
I re-tried, without changing anything.

```
[cwl@cwl-desktop:haskell]$ git clone https://github.com/mwotton/heroku_haskell_demo.git
Initialized empty Git repository in /home/cwl/Studio/haskell/heroku_haskell_demo/.git/
remote: Counting objects: 63, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 63 (delta 23), reused 58 (delta 18)
Unpacking objects: 100% (63/63), done.
[cwl@cwl-desktop:haskell]$ cd heroku_haskell_demo/
[cwl@cwl-desktop:heroku_haskell_demo]$ ls
app  app.hs  Gemfile  Gemfile.lock  Procfile  README  run
[cwl@cwl-desktop:heroku_haskell_demo]$ heroku create
Creating severe-earth-920... done, stack is bamboo-mri-1.9.2
http://severe-earth-920.heroku.com/ | git@heroku.com:severe-earth-920.git
Git remote heroku added
[cwl@cwl-desktop:heroku_haskell_demo]$ git push heroku master
The authenticity of host 'heroku.com (50.19.85.154)' can't be established.
RSA key fingerprint is 8b:48:5e:67:0e:c9:16:47:32:f2:87:0c:1f:c8:60:ad.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'heroku.com,50.19.85.154' (RSA) to the list of known hosts.
Counting objects: 63, done.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (63/63), 5.91 MiB | 40 KiB/s, done.
Total 63 (delta 23), reused 0 (delta 0)

-----> Heroku receiving push
 !     Heroku push rejected, no Rails or Rack app detected

To git@heroku.com:severe-earth-920.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:severe-earth-920.git'
```

**Comment by mwotton** [comment]
Ah, you didn't use the cedar stack. Try "heroku create --stack cedar"

Sent from my exocortex

On 21/08/2011, at 5:56 PM, qzchenwl
reply@reply.github.com
wrote:

**Comment by qzchenwl** [comment]
get one copy of the demo again
and create new one with command "heroku create --stack cedar"
then ...

```
$ git push heroku master
Counting objects: 63, done.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (63/63), 5.91 MiB | 770 KiB/s, done.
Total 63 (delta 23), reused 0 (delta 0)

-----> Heroku receiving push
-----> Ruby app detected
-----> Installing dependencies using Bundler version 1.1.pre.8
       Running: bundle install --without development:test --path vendor/bundle --deployment
       You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       You have added to the Gemfile:
       * source: rubygems repository
 !
 !     Failed to install gems via Bundler.
 !
 !     Heroku push rejected, failed to compile Ruby app

To git@heroku.com:blooming-beach-948.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:blooming-beach-948.git'
```

**Comment by mwotton** [comment]
huh, that's weird. it looks like you don't have a current Gemfile.lock... is the modified-date on it later than the Gemfile?
If you have bundler installed, you could follow the advice heroku gives, or you could just try "touch Gemfile.lock".

**Comment by qzchenwl** [comment]
I tried both and got the same out put as the previous try.

2011/8/22 mwotton <
reply@reply.github.com>

**Comment by mwotton** [comment]
So, I tried this out, and it's failing for me too - it looks like Heroku's made a change that outlaws empty Gemfiles.
I got around it by putting this in the Gemfile:

  source "http://rubygems.org"

  gem "heroku"

and running bundle install.

**Comment by qzchenwl** [comment]
Great! It works!

2011/8/22 mwotton <
reply@reply.github.com>

**Comment by mwotton** [comment]
Delighted to hear it. :) go hack cool stuff

Sent from my exocortex

On 22/08/2011, at 3:34 PM, qzchenwl
reply@reply.github.com
wrote:

**Comment by vcastellm** [comment]
Same error here. Thanks for the workaround.

**Comment by timjb** [comment]
Tried it with the changed Gemfile hack. Heroku accepted the push, but the application [crashed](http://severe-sunset-5336.herokuapp.com/) immediately. I have no idea why because `heroku logs` doesn't give me the error message.

**Comment by justy** [comment]
Thanks Wotto- had a similar issue with a static site but now all is good.

**Comment by tauraloke** [comment]
Oh, it is really great advice. I finally run binary at Heroku.

**Comment by mwotton** [comment]
tauraloke: glad it helped - you don't actually need the workaround any
more, cedar lets you do it directly. Am currently working on a way to
get heroku to compile the app for you too, which ought to help with
bandwidth, as you'd only be pushing git repo changes.

On Wed, Jul 4, 2012 at 12:19 AM, tauraloke
reply@reply.github.com
wrote:

> Oh, it is really great advice. I finally run binary at Heroku.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mwotton/heroku_haskell_demo/issues/2#issuecomment-6735508

## 

A UNIX signature isn't a return address, it's the ASCII equivalent of a
black velvet clown painting. It's a rectangle of carets surrounding a
quote from a literary giant of weeniedom like Heinlein or Dr. Who.
        -- Chris Maeda

**Comment by tauraloke** [comment]
It is interesting. I tried three buildpacks and only one is working (it is your buildpack).
Haskell development looks like very hard but meditative.

**Comment by mwotton** [comment]
hm, do you mean this project, or my forked buildpack? I haven't got it
going yet, afaict :)

On Thu, Jul 5, 2012 at 7:30 AM, tauraloke
reply@reply.github.com
wrote:

> It is interesting. I tried three buildpacks and only one is working (it is your buildpack).
> Haskell development looks like very hard but meditative.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mwotton/heroku_haskell_demo/issues/2#issuecomment-6768108

## 

A UNIX signature isn't a return address, it's the ASCII equivalent of a
black velvet clown painting. It's a rectangle of carets surrounding a
quote from a literary giant of weeniedom like Heinlein or Dr. Who.
        -- Chris Maeda

**Comment by tauraloke** [comment]
I mean this haskell buildpack: https://github.com/mwotton/heroku-buildpack-haskell
I can't create issues at your buildpack version but I am trying using it. Buildpack compiles part of hackages but can't link lib/libgmp.so:

```
Loading package integer-gmp ... <command line>: can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)
```

**Comment by mwotton** [comment]
Yeah, that's not working. This project requires you to build a static binary, the buildpack was intended to allow remote building. Haven't managed to get it working.

**Comment by tauraloke** [comment]
Can Heroku support 32-binary apps (via ia32-libs or something else)?

**Comment by mwotton** [comment]
not sure, haven't tried.
